### ISSUE TITLE
Implement a more robust thresholding technique

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/seq-analysis#1]
@blueboytrl Currently we're only tossing barcodes that have <10 reads for all experiments.

**Comment by tlnagy** [comment]
@blueboytrl The distribution of counts seems roughly normal on a log2 scale:

``` .python
import seq_analysis as seq
import pandas as pd, numpy as np
import seaborn as sns

raw_barcode_data, mapped_barcode_data = seq.map_dataset("et0h_barcodes_to_count.csv")

df = mapped_barcode_data.pivot_table(index=["days", "timepoints", "barcodes", "codons","amino acids", "positions"],
                                         values=["counts", "rel_freq", "rel_wt"])

df = df.unstack("days").unstack("timepoints")

idx = pd.IndexSlice
# Throw out barcodes that have no counts in at least one experiment
df = df[pd.notnull(df.loc[:, idx["counts"]]).sum(axis=1) == 6]

sns.set_style("white")
np.log2(df).plot(kind="kde")
```

![test](https://cloud.githubusercontent.com/assets/1661487/10981254/91fd1170-83bb-11e5-941d-53eed75349dc.png)

**Comment by tlnagy** [comment]
Interestingly most of the distributions look bimodal so we might be able to separate them out cleanly.

**Comment by blueboytrl** [comment]
the left peak should be for the 1?

**Comment by blueboytrl** [comment]
what it looks like if you remove all the counts = 1

**Comment by tlnagy** [comment]
You mean remove all barcodes that have a count 1 in **any** experiment?

**Comment by blueboytrl** [comment]
that will lose a lot, right?

**Comment by tlnagy** [comment]
I used this as the filter

``` python
df = df[df[df == 1].count(axis=1) == 0]
```

it seems to work pretty well:
![test](https://cloud.githubusercontent.com/assets/1661487/10982345/906a7702-83c1-11e5-8ad7-ed8e96058e76.png)

**Comment by tlnagy** [comment]
You can double check this too. That's why I'm pasting all the code up here.

**Comment by tlnagy** [comment]
We only throw out 966 barcodes using this technique

**Comment by blueboytrl** [comment]
ok. we can do this

**Comment by blueboytrl** [comment]
it looks nice

**Comment by tlnagy** [comment]
Once we normalize to raw total counts, we get almost a perfect overlap:

``` python
%load_ext autoreload
%autoreload 2
%pylab --no-import-all
%matplotlib inline

import seq_analysis as seq
import pandas as pd, numpy as np
import seaborn as sns

raw_barcode_data, mapped_barcode_data = seq.map_dataset("et0h_barcodes_to_count.csv")

df = mapped_barcode_data.pivot_table(index=["days", "timepoints", "barcodes", "codons","amino acids", "positions"],
                                         values=["counts", "rel_freq", "rel_wt"])

df = df.unstack("days").unstack("timepoints")

idx = pd.IndexSlice
# Throw out barcodes that have no counts in at least one experiment
df = df[pd.notnull(df.loc[:, idx["counts"]]).sum(axis=1) == 6]

df = df[df[df == 1].count(axis=1) == 0]

sums = df["counts"].sum()

# create a new multiindexed column called rel_freq
new_cols = pd.MultiIndex.from_product([["rel_freq"], ["d1", "d2"], ["t0", "t1", "t2"]])
normed_df = df.loc[:, idx["counts"]]/sums
normed_df = pd.DataFrame(normed_df.values, index=normed_df.index, columns=new_cols)

# add the new column
df = pd.concat([df, normed_df], axis=1)

sns.set_style("white")
np.log2(df["rel_freq"]).plot(kind="kde")
```

![test](https://cloud.githubusercontent.com/assets/1661487/10982504/7c2b5b52-83c2-11e5-93b8-06cd0fef0bd4.png)

**Comment by tlnagy** [comment]
See @lrkenner, we're slowly but surely getting better at this

**Comment by lrkenner** [comment]
You guys are making progress!
What is the X-axis on these graphs?

**Comment by tlnagy** [comment]
It is log counts in the first graph, and log relative frequency in the second. these are by no means final haha.
