### ISSUE TITLE
Problems loading h5 file and t-test filtering issues

### ISSUE THREAD

**Issue by blueboytrl** [tlnagy/seq-analysis#11]
@tlnagy I tried to run the new code.. There are several bugs:

``` python
group_name = "Et0H"
raw, mapped_barcode_data = seq.map_dataset("lanes_new_combined.fastq.h5", group_name)
processed = seq.process_data(mapped_barcode_data)
regressed = seq.regress(processed, group_name, "truseq_primers.csv")
filtered = seq.groupby_filter(regressed)
filtered
```
1. `ValueError: labels ['index'] not contained in axis`

it seems because of this line 
`idx = pd.IndexSlice
raw_barcode_data = raw_barcode_data.loc[idx[matched_group], :].reset_index().drop("index", axis=1)`

2  After I remove **drop("index", axis=1)**, It shows
'''KeyError: 'exp''''

It seems because in the h5 file, you already separated 'exp' to 'days' and 'timepoints' , so we do not need the following lines:
`raw_barcode_data[["days", "timepoints"]] = raw_barcode_data["exp"].str.replace(r"t", "_t").str.split("_", expand=True)`

**Comment by tlnagy** [comment]
All good catches. This is because you are using the new h5 file that follows a new format that I'm testing. The code on github was expecting the old version.

**Comment by blueboytrl** [comment]
so do I need to switch to the old version? Where is it?

**Comment by tlnagy** [comment]
I fixed the loading code to work with the new h5 file format. Let me know if there are any other problems.

**Comment by blueboytrl** [comment]
and also
1  why the pval is Nan for those have more than 1 counts?
<img width="416" alt="screen shot 2015-11-12 at 10 33 09 am" src="https://cloud.githubusercontent.com/assets/14592557/11127355/d68f638e-8928-11e5-91a7-b0cea1d95e0b.png">

Is it because they have 1 counts in either one of the two days?
2  Shouldn't this line
`def sig_filter(d1, d2):
        if len(d1) == 1 and (float(d1) - float(d2))**2 > single_bc_cutoff:`
be:

`````` python
def sig_filter(d1, d2):
        if (len(d1) == 1 or len(d2)==1) and (float(d1) - float(d2))**2 > single_bc_cutoff:```

because now we consider d1 and d2 separately?
``````

**Comment by tlnagy** [comment]
Again good catch. I must've missed that when I changing the code from the days having the same number of barcodes to not. It should be either or.

**Comment by tlnagy** [comment]
Another problem is that the `size` was only the number of barcodes on day1. I'm writing a quick patch and testing it.

**Comment by blueboytrl** [comment]
how about showing size of d1 and size of d2 separately

**Comment by tlnagy** [comment]
Yeah, that was my first thought too. Already doing that, trying to see where they differ.

**Comment by tlnagy** [comment]
I found the major bug. I can't do `len(d1)` vs `len(d2)` because they are the exact same length because pandas pads missing values with `NaN` when doing a groupby. I have to count all non-`NaN` values and that's the true length.

**Comment by blueboytrl** [comment]
I see

**Comment by blueboytrl** [comment]
did you already fix it?

**Comment by tlnagy** [comment]
## I’m fixing it right now. Hold tight.

Tamas Nagy
University of California, San Francisco
http://www.tamasnagy.com

**Comment by tlnagy** [comment]
I pushed a preliminary version. The problem are cases like when one day has 2 barcodes and the other has 1. What to do then?

**Comment by blueboytrl** [comment]
That's indeed a problem... use the mean of the day that have more than 1 counts and then compare the distance?

**Comment by tlnagy** [comment]
There are still ~300 barcodes that only show up on one day. I left those in because why not.

**Comment by blueboytrl** [comment]
@tlnagy   another bug:
Control doesn't have d2, so we need to distinguish if the group is control or not

**Comment by tlnagy** [comment]
Why would you run the t-test filter on the control? The whole point is to combine across days? I would probably just `groupby(level=["codon","position"]).mean()` for the control after the regression step. 

I'm working on a bootstrap implementation for precisely that reason though. There is no way to handle a missing day with the t-test approach. Also, it might not be the best idea to combine the days. Maybe looking at them separately is interesting too.

**Comment by blueboytrl** [comment]
O, I was wrong.. I just threw all groups into the filter

Sent from my iPhone

On Nov 12, 2015, at 11:55 AM, Tamas Nagy <notifications@github.com<mailto:notifications@github.com>> wrote:

Why would you run the t-test filter on the control? The whole point is to combine across days? I would probably just groupby(level=["codon","position"]).mean() for the control after the regression step.

I'm working on a bootstrap implementation for precisely that reason though. There is no way to handle a missing day with the t-test approach. Also, it might not be the best idea to combine the days. Maybe looking at them separately is interesting too.
