### ISSUE TITLE
Licensing of data/ 

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/seq-analysis#15]
@dmyersturnbull any progress on this?

**Comment by dmyersturnbull** [comment]
I have a clone with all data files scrubbed. Am I good to force commit?

**Comment by tlnagy** [comment]
Go for it. I'll keep my copy out of sync in case anything goes wrong.

**Comment by dmyersturnbull** [comment]
I think master is protected, preventing me from force pushing. Apparently you can disable it in settings. Otherwise, I think you may need to do it instead.

**Comment by tlnagy** [comment]
I deprotected master. Let me know if it still doesn't work.

**Comment by dmyersturnbull** [comment]
Done.
