### ISSUE TITLE
Develop relative fitness score to collapse timepoints into one value

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/seq-analysis#2]
@blueboytrl We still need to actually implement the relative fitness score code so that we can collapse time points into a single value that represents that barcode's "performance".

TODO

**Comment by tlnagy** [comment]
I'm working on developing the fitness score and I have some interesting results. I first apply a linear regression function to the log2(relative to wt) data and then I plot the distributions of the r^2 and standard error.

``` python
%load_ext autoreload
%autoreload 2
%pylab --no-import-all
%matplotlib inline

import seq_analysis as seq
import pandas as pd, numpy as np
import seaborn as sns
import scipy
sns.set_style("white")

df = seq.process_data()

df2 = np.log2(df["rel_wt"])

gen_times = {"d1":[0, 3.14, 5.14], "d2":[0, 1.76, 4.02]}

def linregress_func(xs, ys):
    slope, intercept, r, p, stderr = scipy.stats.linregress(xs, ys)
    return pd.Series({"slope":slope, "r^2":r**2 ,"stderr":stderr}, index=["slope", "stderr", "r^2"], name="stats")

df3 = df2.stack("days").apply(lambda ys: linregress_func(gen_times[ys.name[-1]], ys), axis=1)
df3.unstack("days")["r^2"].plot(kind="kde")
plt.savefig("test.png", dpi=300)
```

![test](https://cloud.githubusercontent.com/assets/1661487/10989766/649270a0-8400-11e5-94c5-5abb4a904d36.png)

``` python
df3.unstack("days")["stderr"].plot(kind="kde")
```

![test2](https://cloud.githubusercontent.com/assets/1661487/10989769/6cd4e5c2-8400-11e5-90da-10976e9ff2b9.png)

**Comment by tlnagy** [comment]
It looks as though the data that we got from the second data is more linear with a smaller standard err and more r^2 density close 1. I'm going to explore some filtering techniques. 

We also don't necessarily want to throw out the low r^2 barcodes. They could be interesting.

**Comment by tlnagy** [comment]
@blueboytrl @rugusf thoughts?

**Comment by rugusf** [comment]
Interesting...so you're saying we can still count the fitness scores from the left population? can we trust their fitness scores because of the low r2 values?

**Comment by tlnagy** [comment]
No, I mean that there might be some interesting biological reason for that happening or it might be a technical defect or something non-intuitive. I have no idea. We should explore it.

**Comment by blueboytrl** [comment]
there might be... But now let's filter them out first

**Comment by tlnagy** [comment]
Filtering could work...

``` python
df4 = df3.unstack("days")
f, axes = plt.subplots(1,2, sharey=True, figsize=(10, 4))
df4[df4[df4["r^2"] < 0.95]["r^2"].count(axis=1) == 2]["slope"].plot(kind="kde", ax=axes[0])
axes[0].set_title("r^2 < .95")
df4[df4[df4["r^2"] > 0.95]["r^2"].count(axis=1) == 2]["slope"].plot(kind="kde", ax=axes[1])
axes[1].set_title("r^2 > .95")
for ax in axes: ax.set_xlabel("slope")
plt.ylim((0, 4))
plt.savefig("test3.png", dpi=300)
```

![test3](https://cloud.githubusercontent.com/assets/1661487/10991147/a0843990-840f-11e5-9bbd-7e25f99f6963.png)

**Comment by tlnagy** [comment]
Looking at only high r^2 values seems to sort our barcodes into two categories, ones that are roughly the same as WT and those that are a lot worse (peak around -0.5).

**Comment by blueboytrl** [comment]
that looks nice. how many did we throw away

**Comment by blueboytrl** [comment]
and it seems that those that have r2<.95 are roughly same as wt

**Comment by blueboytrl** [comment]
.95 maybe too high?

**Comment by tlnagy** [comment]
Ruilin, I wouldn't read to much into that. The figure above with the r^2 values shows that there are two populations. The <.95 includes the population around r^2=0, which means that we can't say anything about them (i.e. the relationship is non-linear, etc). I had the requirement that they have to >.95 on both days so we threw out 92% of barcodes (i.e. 92% of 15,533)

**Comment by blueboytrl** [comment]
![image](https://cloud.githubusercontent.com/assets/14592557/10991350/5694783e-8411-11e5-969c-8d1f7b7aefc2.png)
that is a lot... what about set it to 0.5?

**Comment by tlnagy** [comment]
I thought you might ask that so...I'll let this graph speak for itself

``` python
xs = np.linspace(0, 1, 100)
ys = np.vectorize(lambda x: len(df4[df4[df4["r^2"] > x]["r^2"].count(axis=1) == 2]))
plt.plot(xs, (1-ys(xs)/len(df4))*100)
sns.axlabel("r^2 cutoff value", "percent barcodes thrown out")
plt.savefig("test4.png", dpi=300)
```

![test4](https://cloud.githubusercontent.com/assets/1661487/10991402/d6f6c40a-8411-11e5-9e57-ecd36618bd51.png)

**Comment by blueboytrl** [comment]
nice graph! so we  will loss half when it equals 0.5....how do you think

**Comment by tlnagy** [comment]
I decided to visualize our slopes as a sanity check...so I hacked this up. The code is garbage and needs a lot of cleanup, but it's pretty cool.

``` python
import itertools
xs = np.linspace(0, 6)
df5 = df2.stack("days")

m, b = df3[["slope", "intercept"]].values.T

idxs = np.random.randint(0, len(m), size=10)

colors = sns.color_palette(n_colors=10)

for idx, color in zip(idxs, colors):
    multiidx = df3.iloc[idx, :].name
    day = multiidx[-1]
    plt.plot(xs, m[idx]*xs+b[idx], c=color)
    tps = df5.loc[multiidx, :]
    plt.scatter(gen_times[day], tps)
    plt.text(6, m[idx]*6+b[idx], "{:.3}".format(df3.iloc[idx, :]["r^2"]))
sns.axlabel("generation", "rel_wt_median")
plt.savefig("test6.png", dpi=300)
```

The numbers on the right side are R^2 
![test6](https://cloud.githubusercontent.com/assets/1661487/10992003/d29e60b6-8416-11e5-8b71-821125568bfd.png)

**Comment by tlnagy** [comment]
I spent the last twenty minutes fighting matplotlib, but I finally got it to color the points. I also added stderr to the right of the R^2 values:

![test7](https://cloud.githubusercontent.com/assets/1661487/10992469/e95e8f02-841a-11e5-9425-5c96f6a5faae.png)

I think the important takeaway is that we shouldn't use R^2, standard error is much better. This makes sense because standard error measures the average distance that points are from line. 

~~We can use R^2 to classify points as being helpful or harmful as compared to WT.~~

**Comment by blueboytrl** [comment]
i think r^2 takes standard error into account.. So I think maybe still use R^2?

![](http://www.graphpad.com/guides/prism/6/curve-fitting/_bm36.png)

![](http://www.graphpad.com/guides/prism/6/curve-fitting/_bm37.png)

**Comment by blueboytrl** [comment]
And I think r^2 and standard error do the similar thing..but usually people use R^2 to describe the goodness of a linear fit

**Comment by blueboytrl** [comment]
and how could we ''use **R^2** to classify points as being helpful or harmful as compared to WT''? Shouldn't it be the **slope**?

**Comment by tlnagy** [comment]
No. They measure different things. For example, look at the purple line (2nd from the top) in the my last graph. The R^2 value is very low at 0.0512, but the standard error is 0.0797 (we want a low standard error). We would throw this line out if we used R^2 as the cutoff, but it is obviously a pretty good fit because the line goes through almost each point.

**Comment by tlnagy** [comment]
Yeah, my last point is wrong. We should use the slope.

**Comment by blueboytrl** [comment]
It is weird.....How could it possible for the purple line the r^2 is so low...

**Comment by tlnagy** [comment]
It makes sense. Pearson's correlation coefficient measures how correlated x and y are. Well, if you have a flat line that means you are changing x and y doesn't change, aka they are not correlated so you get a low R^2.

**Comment by blueboytrl** [comment]
o, i understand..r^2 describes the linear correlation..

**Comment by tlnagy** [comment]
yes. That's not what we want. We want a metric for how well our regression line describes our data (i.e. is the slope representative of the data). Standard error is the way to go.

**Comment by blueboytrl** [comment]
I agree

**Comment by tlnagy** [comment]
And this is a lot nicer:

``` python
df4 = df3.unstack("days")
xs = np.linspace(0, 1, 100)
ys = np.vectorize(lambda x: len(df4[df4[df4["stderr"] > x]["stderr"].count(axis=1) == 2]))
plt.plot(xs, (ys(xs)/len(df4))*100)
plt.xscale("log")
sns.axlabel("stderr cutoff value", "percent barcodes thrown out")
plt.ylim((0,101))
sns.despine(offset=10)
plt.tight_layout()
plt.savefig("test5.png", dpi=300)
```

![test5](https://cloud.githubusercontent.com/assets/1661487/11005862/3c3e3be6-8475-11e5-9be1-e5cb6e833c75.png)

**Comment by tlnagy** [comment]
@rugusf and @blueboytrl I just pushed the regression changes. You should be able to use them as follows:

``` python
%load_ext autoreload
%autoreload 2
import seq_analysis as seq

processed_data = seq.process_data()

# run the linear regression code and average the slopes between days
regressed_data = seq.regress(processed_data, average_days=True)

# we don't need the multiindex now that we averaged the days and 
# collapsed the timepoints
regressed_data.reset_index()
```

**Comment by blueboytrl** [comment]
cool!

**Comment by blueboytrl** [comment]
``` python
processed_data = seq.process_data()

# run the linear regression code and average the slopes between days
regressed_data = seq.regress(processed_data, average_days=False)


regressed_data.head(10)
```

<img width="560" alt="screen shot 2015-11-06 at 1 04 30 pm" src="https://cloud.githubusercontent.com/assets/14592557/11008673/f7b9a430-8486-11e5-9800-26936da9ae3f.png">

like barcode 1, there are huge difference between day1 and day2, do we still average them? or another filter here?

**Comment by blueboytrl** [comment]
``` python
sns.regplot(regressed_data['d1'],regressed_data['d2'])
```

![image](https://cloud.githubusercontent.com/assets/14592557/11009009/04a2d656-8489-11e5-9364-3377a57005da.png)

the correlation between d1 and d2 is not very well

**Comment by tlnagy** [comment]
That's horrible. We'll probably have to filter based on the standard error of a regression line between d1 and d2

**Comment by tlnagy** [comment]
Plotting the residuals after fitting a regression line to your graph...

![test8](https://cloud.githubusercontent.com/assets/1661487/11010299/c2e942e0-8492-11e5-8306-a4d0f2044f87.png)

**Comment by blueboytrl** [comment]
we should not use the **regression**... Because we are expecting y = x.. but the slope for regression is not 1... We will just use deviation of d1 and d2, which is (d1-d)^2+(d2-d)^2.. or just the distance between d1 and d2, (d1-d2)^2

**Comment by blueboytrl** [comment]
and filter based on that distribution

**Comment by tlnagy** [comment]
Yeah, I was wrong about using the standard error. 

We are expecting that d1 and d2 are correlated so using the residuals for filtering after fitting a regression line seems to be best way. Say, only take barcodes that have residuals with abs values less than 0.25. That way we remove barcodes that vary a bunch between d1 and d2.

**Comment by blueboytrl** [comment]
there is no meaning to do a regression using only two point.. because you can always draw a line which goes through the two points so the residues =0... I think here we can use residues when fitting by y = x, instead of regression

**Comment by tlnagy** [comment]
I mean regression using x=slopes from day one,  y= slopes from day two. That is, finding the regression line between d1 and d2 and then looking at the residual scores on per-barcode basis. See what I mean?

**Comment by blueboytrl** [comment]
I see.. But we expect y =x, not just correlation.  When you remove every barcode in your way, the regression changes everytime

**Comment by tlnagy** [comment]
You're right, but the thing that worries me is that maybe we shouldn't merge d1 and d2 on the per-barcode level. Maybe it would be better to merge them on the per-codon/position level. There may be too much noise here.

**Comment by blueboytrl** [comment]
o, i know what you mean. i agree with that

**Comment by blueboytrl** [comment]
```python
regressed_data['(d1-d2)^2'] = np.square(regressed_data['d1'] - regressed_data['d2'])

plt.figure(figsize=(8,5))
plt.xlim(0,.1)
sns.distplot(regressed_data['(d1-d2)^2'])```
![image](https://cloud.githubusercontent.com/assets/14592557/11011625/f5dae346-849e-11e5-8cfe-65318077d883.png)


Here I plot the difference between d1 and d2

**Comment by blueboytrl** [comment]
Here i plotted the distribution of differences between d1 and d2 on barcodes level

``` python
regressed_data['(d1-d2)^2'] = np.square(regressed_data['d1'] - regressed_data['d2'])

plt.figure(figsize=(8,5))
plt.xlim(0,.1)
sns.distplot(regressed_data['(d1-d2)^2'])
```

![image](https://cloud.githubusercontent.com/assets/14592557/11011640/0f8d6462-849f-11e5-8ee1-b7040dd2f573.png)

**Comment by blueboytrl** [comment]
I use distance 0.02 as a cutoff.. It looks much better. It removed 1301, which is 11.7% of the data.

``` python
df = regressed_data[regressed_data['(d1-d2)^2']<0.02]
print (len(regressed_data)-len(df),(len(regressed_data)-len(df))/len(regressed_data))
plt.figure(figsize=(8,8))
plt.xlim(-1,0.5)
plt.ylim(-1,0.5)
sns.regplot(df['d1'],df['d2'])
```

![image](https://cloud.githubusercontent.com/assets/14592557/11011732/2ad9c17e-84a0-11e5-8db1-dc880bd29006.png)

**Comment by blueboytrl** [comment]
I tried different cutoff value

``` python
f, axes = plt.subplots(2,2, sharey=True, figsize=(10, 10))
plt.xlim(-1,0.5)
plt.ylim(-1,0.5)
df = regressed_data[regressed_data['(d1-d2)^2']<0.08]
data_lose = (len(regressed_data)-len(df))/len(regressed_data)
sns.regplot(df['d1'],df['d2'],ax = axes[0][0],label = 'cutoff=0.08\nlose %.2f'%(data_lose*100)+'%')
axes[0][0].legend(loc = 'upper left',fontsize = 12)

df = regressed_data[regressed_data['(d1-d2)^2']<0.06]
data_lose = (len(regressed_data)-len(df))/len(regressed_data)
sns.regplot(df['d1'],df['d2'],ax = axes[0][1],label = 'cutoff=0.06\nlose %.2f'%(data_lose*100)+'%')
axes[0][1].legend(loc = 'upper left',fontsize = 12)

df = regressed_data[regressed_data['(d1-d2)^2']<0.04]
data_lose = (len(regressed_data)-len(df))/len(regressed_data)
sns.regplot(df['d1'],df['d2'],ax = axes[1][0],label = 'cutoff=0.04\nlose %.2f'%(data_lose*100)+'%')
axes[1][0].legend(loc = 'upper left',fontsize = 12)

df = regressed_data[regressed_data['(d1-d2)^2']<0.02]
data_lose = (len(regressed_data)-len(df))/len(regressed_data)
sns.regplot(df['d1'],df['d2'],ax = axes[1][1],label = 'cutoff=0.02\nlose %.2f'%(data_lose*100)+'%')
axes[1][1].legend(loc = 'upper left',fontsize = 12)
```

![image](https://cloud.githubusercontent.com/assets/14592557/11012123/8c79f666-84a4-11e5-8c3e-f87d20bd4642.png)

**Comment by blueboytrl** [comment]
How do you guys think? @tlnagy   @rugusf

**Comment by tlnagy** [comment]
Do you want to do a plot like the one I had where you plot the number of barcodes thrown out vs the cutoff value?

Also, we might need to explore grouping on codon and then doing the filtering...the error in individual barcodes might be higher, but the group as a whole might be more accurate

**Comment by blueboytrl** [comment]
``` python
data_lose = []
for i in np.linspace(0.0,regressed_data['(d1-d2)^2'].max(),num = 100):
    df = regressed_data[regressed_data['(d1-d2)^2']<i]
    data_lose.append((len(regressed_data)-len(df))/len(regressed_data)*100)
plt.xlim(0,0.1)
plt.xlabel('(d1-d2)^2 cutoff')
plt.ylabel('percentage loss')
plt.plot(np.linspace(0.0,regressed_data['(d1-d2)^2'].max(),num = 100),data_lose,'r-')
```

![image](https://cloud.githubusercontent.com/assets/14592557/11019163/1b659186-85a0-11e5-89c0-157b72f83fd5.png)

**Comment by blueboytrl** [comment]
I think quality control should do on barcodes level, because barcode counts are what we directly got from experiment

**Comment by blueboytrl** [comment]
I found one bug in your code:

``` python
def process_data(csv_filepath = "et0h_barcodes_to_count.csv"):
    if mapped_barcode_data is None or og_filepath != csv_filepath:
        print("Data not yet loaded, loading now...\n", flush=True)
        map_dataset(csv_filepath)
```

when loading control file, it will not work..
Just delete **_or og_filepath != csv_filepath**_

**Comment by blueboytrl** [comment]
and also the regress function should be re-written for control file

**Comment by tlnagy** [comment]
I pushed a new change that fixes the bug that you pointed out.

**Comment by tlnagy** [comment]
~~What bug did you find in the regress function output? It seems to work fine on the control file data, giving the right results. The wording of the output isn't best here:~~

```
regressing...
thresholding using stderr <0.1 required for all days
discarding 4524 barcodes...
```

~~but does the right thing.~~

Actually, I see what you mean. The generation times are wrong. I'll fix that.

Yes, that is what I mean

**Comment by tlnagy** [comment]
> I think quality control should do on barcodes level, because barcode counts are what we directly got from experiment

They are, but I want to see whether grouping them together gives us better results than looking at each one separately. There is inherent noise in our method so it'll be nice to be a bit more robust in our analysis.

**Comment by rugusf** [comment]
So when the regress function is used a series is generated rather than a dataframe...would I just have to concat. it to our existing structure? Or is the information available in the series itself...

**Comment by tlnagy** [comment]
It has all the necessary information. I assume you've run the following (on the latest codebase!):

``` python
import seq_analysis as seq
_, mapped_barcode_data = seq.map_dataset("et0h_barcodes_to_count.csv")
processed_barcodes = seq.process_data(mapped_barcode_data)
df = seq.regress(processed_barcodes)
```

then you can just run

``` python
df.reset_index()
```

to get
<img width="598" alt="screen shot 2015-11-08 at 14 34 54" src="https://cloud.githubusercontent.com/assets/1661487/11023167/f81e82ce-8625-11e5-880d-f385ac872fb2.png">

**Comment by rugusf** [comment]
Oh, it looks like I get a series only if I choose to average the days. So, looking at the discussion, it might be better to average the days on a codon or a.a. position level? Or should they be averaged on a barcode level, since there is thresholding?

**Comment by blueboytrl** [comment]
@tlnagy so now we need to pass the generation time to regression function?

**Comment by tlnagy** [comment]
> Oh, it looks like I get a series only if I choose to average the days. So, looking at the discussion, it might be better to average the days on a codon or a.a. position level? Or should they be averaged on a barcode level, since there is thresholding? 

Yes, it might be because the variability in slopes might be too high on a specific barcode level. What do you mean by thresholding here?

> @tlnagy so now we need to pass the generation time to regression function?

Only for the control. The default value applies for our data. It's not the best solution, but it was the quickest. I might come up with something better if I have time.

**Comment by rugusf** [comment]
I thought we were thresholding based on (d1-d2)^2 cutoff but it looks like we're only thresholding for the regression based on standard error, my bad.

**Comment by tlnagy** [comment]
> I thought we were thresholding based on (d1-d2)^2 cutoff but it looks like we're only thresholding for the regression based on standard error, my bad.

We haven't yet decided on a thresholding technique for combining the replicates. @blueboytrl and I are still working on it. 

Also, if you guys run into any problems that aren't directly related to this specific thresholding problem then could you open a new issue. This thread is getting a bit unwieldy.

**Comment by tlnagy** [comment]
Alright. What about this, we could group barcodes by position and codon and then run a t-test or a rank-sum test to determine whether the slopes differ significantly between replicates and toss out the ones that do? 

I expect the distribution of slopes to be roughly normal so we could use the parametric t-test to do this. I'm working on this right now.

**Comment by blueboytrl** [comment]
What if there is significant difference?  Will you just throw away the data for this position or codon?

I think maybe just do the threshold on barcodes.. According to this graph, if we use 0.02 as a cutoff, we won't lose many data, but the linearity is much better
![image](https://cloud.githubusercontent.com/assets/14592557/11023475/f5f19c6c-862e-11e5-9c09-dd4b459f6c44.png)

**Comment by tlnagy** [comment]
The thing is...if there is a significant difference between replicates for that position and codon, we should be worried about that position and code. The benefit of this approach is that you leverage the information given to you both by the multiple barcodes targeting one position-codon (mutation) and from having replicates. I think this would be the most robust to noise.

**Comment by blueboytrl** [comment]
alright, let's do that...

**Comment by blueboytrl** [comment]
Here I got the heatmap of codons at different position
![image](https://cloud.githubusercontent.com/assets/14592557/11023538/c82a3bc0-8630-11e5-837a-29a3f3d144ff.png)
The blanks are for missing data

**Comment by tlnagy** [comment]
What cutoff did you use? And then did you average the barcodes for the same codon-position?

**Comment by blueboytrl** [comment]
I just used the distance 0.02 as cutoff.. i will use the new data after you finish the t-test..
Yes, I averaged the value for the same posiiton

``` python
codons = df['codons'].unique()
pos = sorted(list(df['positions'].unique()))

codon_pos = pd.DataFrame(columns=codons,index = pos)

for position in pos:
    new_df = df[df['positions']==position]
    codon = list(new_df['codons'])
    for i in codon:
        codon_pos.loc[position,i] = new_df[new_df['codons']==i]['average'].mean()
```

**Comment by rugusf** [comment]
so I grouped based on amino acid at each position and d1/d2 looks more correlated than on a barcode basis
I hope I'm doing this right...

``` python
cur = df
aa_pos = cur.groupby(['amino acids','positions'])
aa_pos = aa_pos.aggregate(np.mean)
sns.regplot(aa_pos['d1'],aa_pos['d2'])
plt.savefig("test.png", dpi=300)
```

![test](https://cloud.githubusercontent.com/assets/11674879/11023765/9ba1c9dc-8636-11e5-8853-e4edac35286e.png)

**Comment by rugusf** [comment]
or maybe it looks more correlated since there are less values..I don't know

**Comment by blueboytrl** [comment]
can you plot the x-axis and y-axis in the same scale,say(-0.8 ~ 0.4)? or plot y = x

**Comment by blueboytrl** [comment]
here is the heatmap for control
![image](https://cloud.githubusercontent.com/assets/14592557/11023800/6661d9f0-8637-11e5-8b5e-51e368e7d673.png)

**Comment by rugusf** [comment]
![test](https://cloud.githubusercontent.com/assets/11674879/11023841/2dc31158-8638-11e5-863f-415bcc36d4b8.png)

**Comment by tlnagy** [comment]
If I filter by those codon-positions that don't significantly differ between replicates and plot the same thing that fatima has:

![test10](https://cloud.githubusercontent.com/assets/1661487/11023969/0345e20e-863b-11e5-9c49-1d813aed9a93.png)

**Comment by rugusf** [comment]
what was your filtering criteria?

**Comment by tlnagy** [comment]
pval > 0.05. As you can tell, we eliminated 300 of the codon-positions that varied the most between replicates.

**Comment by blueboytrl** [comment]
@tlnagy how many data were lost? can you also plot the cutoff-datat hrown out curve?

**Comment by tlnagy** [comment]
The other question is what should I do with codon-positions which have only one barcode? I can't handle those with the t-test approach.

**Comment by blueboytrl** [comment]
how about doing cutoff based on distance distribution?

**Comment by tlnagy** [comment]
>  how about doing cutoff based on distance distribution?

That's what I was thinking. Combine the two. Use your distance metric for mutants (codon-positions) that have only one barcode and the t-test for ones with >1 barcode.

**Comment by rugusf** [comment]
This test you did between d1 and d2 populations for a certain codon-position...is the number of barcodes for each codon-position a good enough number to form a comparison?

**Comment by tlnagy** [comment]
Yes. It should be. See this: https://stats.stackexchange.com/questions/37993/is-there-a-minimum-sample-size-required-for-the-t-test-to-be-valid

**Comment by tlnagy** [comment]
I'm closing this issue because it is a monster. **Please open new issues for specific questions.**
