### ISSUE TITLE
Improve cutoff for codon-positions with small numbers of barcodes

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/seq-analysis#5]
@rugusf @blueboytrl We should explore ways to improve the cutoffs for codon positions where we only have 1 or 2 unique barcodes mapped. The variance is probably due to technical noise because barcodes for the same codon-position should be the same. 

Plotting the bootstrapped mean of standard deviation against the number of unique barcodes mapped to a codon-position gives:

![test11](https://cloud.githubusercontent.com/assets/1661487/11027504/b686fca2-866a-11e5-9dc9-3e696abf3b47.png)

![test11](https://cloud.githubusercontent.com/assets/1661487/11027448/498cebf2-866a-11e5-90c2-90effcc99c87.png)

*The lines are the 95% confidence interval

---

It seems that we can expect roughly 0.05 and 0.07 as the variance due to technical noise on days 1 and days 2, respectively. It looks pretty consistent. We could leverage this to improve our distance cutoff

**Comment by blueboytrl** [comment]
I was not quite clear about the graph.. The std on the y-axis is the std of fitness of the barcodes for the codons that have x barcodes counts?

**Comment by tlnagy** [comment]
Almost. The `y` is the standard deviation in slopes among the barcodes mapping to a codon-position with `x` number of barcodes.

**Comment by tlnagy** [comment]
mean standard deviations in codon-position groups

```
d1_std    0.050248
d2_std    0.070732
dtype: float64
```

**Comment by tlnagy** [comment]
This issue is outdated now. We're not using cutoffs in this way any more.
