### ISSUE TITLE
Heatmaps

### ISSUE THREAD

**Issue by blueboytrl** [tlnagy/seq-analysis#6]
@rugusf  @tlnagy Here I plotted the heatmaps for **amino acids--codons** against **position** for both menadione and control, using new cutoff data.  Codons for same amino acids are put together.
![control_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11027804/ace83c76-866d-11e5-936b-10e4d022c035.png)
![et0h_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11027805/aceacbc6-866d-11e5-87b2-a45cb2a4e606.png)

**Comment by tlnagy** [comment]
That's pretty cool. Seems like there are a lot more negative slopes in the menadione sample, which makes sense considering the additional pressure on the yeast.

**Comment by blueboytrl** [comment]
We had so few data.. a lot of blanks there

**Comment by rugusf** [comment]
Here's my heat map for position vs. AA for mean fitness values. Still have to figure out formatting. @blueboytrl How did you color missing data values as grey?
![hmap](https://cloud.githubusercontent.com/assets/11674879/11027923/d68b89b0-866e-11e5-8977-ac91d177d4b9.png)

**Comment by tlnagy** [comment]
> We had so few data.. a lot of blanks there

We tossed a lot of data with all the filtering we did. We can refine that once we start to work on #3.

**Comment by tlnagy** [comment]
Also @blueboytrl it would be cool if you could refine your heatmap generation code and commit it to the repo so that @rugusf and I can also use it.

**Comment by rugusf** [comment]
It seems like codons for a AA are not put together...

**Comment by tlnagy** [comment]
> It seems like codons for a AA are not put together...

Yeah, I noticed that too. We'll also have to explore various AA groupings (hydrophobic together, etc, etc)

**Comment by blueboytrl** [comment]
@rugusf  @tlnagy I will fix it..  
for the heatmap, I use **mask** 

``` python
mask = df.T.isnull()
sns.heatmap(df.T,mask = mask)
```

And all the nans are grey

**Comment by tlnagy** [comment]
@rugusf with regards to your AA vs position heatmap. How are you aggregating the data? It might be better to use t-tests again except on an aa-position level. I should be able to write a generic function to handle both cases pretty easily. I see you mention this in #7

**Comment by rugusf** [comment]
@tlnagy unless we end up clustering the AAs?

**Comment by rugusf** [comment]
@tlnagy I'm just aggregating on barcodes that correspond to a specific AA at the same position. Data is grouped by AA then by position.

**Comment by tlnagy** [comment]
> I'm just aggregating on barcodes that correspond to a specific AA at the same position. Data is grouped by AA then by position.

On which dataset are you running the aggregation function? Is it on the output of the new t-test significance function? How are you aggregating the data, the mean of codon-positions for that AA?

**Comment by blueboytrl** [comment]
Here they are.
![control_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11028321/522a0918-8672-11e5-96d9-7ee8ce775011.png)
![et0h_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11028322/522da26c-8672-11e5-9b8f-0448cbf89723.png)

**Comment by rugusf** [comment]
> On which dataset are you running the aggregation function? Is it on the output of the new t-test significance function? How are you aggregating the data, the mean of codon-positions for that AA?

on regressed barcodes dataset...I haven't done anything with the new t test function. I took the mean of d1 and d2 after aggregating.

**Comment by blueboytrl** [comment]
I mapped the wt ubiquitin sequence to the position.. quite interesting for  **K27, K48, R42, R72** in menadione sample.

![control_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11029296/eacc71bc-867a-11e5-9e1e-b7c3d8376139.png)

![et0h_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11029295/eac88746-867a-11e5-8383-3a624e8943de.png)

**Comment by rugusf** [comment]
with fixed layout:
![hmaptest](https://cloud.githubusercontent.com/assets/11674879/11041649/ef23ffee-86c7-11e5-924f-0dccb994868c.png)

**Comment by rugusf** [comment]
Also a note: for control and mena heatmaps..it's better if you set the vmax and vmin to the same values so you can directly compare the heat maps

**Comment by blueboytrl** [comment]
I changed the bar and the background color
![control_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11042068/fd80bc06-86c9-11e5-8220-66f925d35436.png)
![et0h_codon_heatmap](https://cloud.githubusercontent.com/assets/14592557/11042069/fd8fea46-86c9-11e5-8046-9d6515f7262d.png)

**Comment by tlnagy** [comment]
My newest commit let's you apply the t-test to any arbitrary grouping...

``` python
...
df = seq.regress(processed_barcodes)
df.index.names

FrozenList(['barcodes', 'codons', 'amino acids', 'positions'])
```

so those are all the indices that we can group on. If I want AA-position I can do:

``` python
filtered = seq.groupby_filter(df, levels=["amino acids", "positions"])
```

**Comment by tlnagy** [comment]
@rugusf @blueboytrl Doing the days independently gets us ~800 (!!) extra codon-positions. 3078 vs the former 2241. I haven't checked how barcodes the new additions have though. The latest commit 87441d8 has some of the changes.

**Comment by blueboytrl** [comment]
Great! But it seems the code still throws away barcodes on barcode level??
