### ISSUE TITLE
AA vs. position

### ISSUE THREAD

**Issue by rugusf** [tlnagy/seq-analysis#7]
Things to do?
- [x] remove @/0 pos values
- [x] add in WT fitness for native residues at each position
- [x] order amino acids by type
- [x] integrate and filter d1 and d2 for AA-pos data <- use same approach as codon-pos data?
- [x] make heat map for control data

**Comment by rugusf** [comment]
updated heat maps...we're still missing data
![control](https://cloud.githubusercontent.com/assets/11674879/11174581/cdc6385e-8bda-11e5-8def-0507b2e0dcb3.png)
![mena](https://cloud.githubusercontent.com/assets/11674879/11174582/cde426de-8bda-11e5-97e3-fbd17bd2263d.png)

**Comment by rugusf** [comment]
can you guys give me some direction in sorting the aa's by type? can I input some dict/list or something?

**Comment by blueboytrl** [comment]
Here are the heatmaps for all groups after subtracting control
It seems our group doesn't have special pattern compared to control,, But Group PyND and Shmoo have interesting decreased fitness at k63 compared to control. 

![et0h_to_control_amino acids_heatmap](https://cloud.githubusercontent.com/assets/14592557/11174654/30e2a354-8bdc-11e5-8c2c-b862d28954f6.png)
![pynd_to_control_amino acids_heatmap](https://cloud.githubusercontent.com/assets/14592557/11174658/3cb9af38-8bdc-11e5-8175-a1bbe38f0af3.png)
![shmoo_to_control_amino acids_heatmap](https://cloud.githubusercontent.com/assets/14592557/11174661/44d89238-8bdc-11e5-8c65-fb604955efef.png)
![whangee_to_control_amino acids_heatmap](https://cloud.githubusercontent.com/assets/14592557/11174664/494ed6ba-8bdc-11e5-96d1-80fd0aadba66.png)

**Comment by rugusf** [comment]
you forgot to give the same value scale ( I used -0.9 to 0.9)
here's the code for my heat maps:

``` python
plt.figure(figsize=(20,5))
sns.heatmap(trans_aa_pos[~isnan(trans_aa_pos)], linewidths = 0.001, square = True, vmin = -0.9, vmax = 0.9)
plt.yticks(rotation=0)
plt.title('Menadione Fitness Values')
plt.savefig("mena.png", dpi=300)
```

**Comment by rugusf** [comment]
Are you subtracting control values or taking a log2 ratio to control values?

**Comment by rugusf** [comment]
Here's sorting the AAs:

``` pymol
trans_aa_pos_ctrl.reindex(['G', 'A', 'V', 'I', 'L', 'M', 'F', 'Y', 'W', 'C', 'S', 'T', 'P', 'N', 'E',
                          'D', 'Q', 'H', 'K', 'R', '*'])
```

![control](https://cloud.githubusercontent.com/assets/11674879/11175896/33d62a9e-8bec-11e5-91d6-d694ad45c583.png)
![mena](https://cloud.githubusercontent.com/assets/11674879/11175897/33eaf212-8bec-11e5-834e-6447187f3f83.png)

**Comment by rugusf** [comment]
Fold Change: ...can't make much out of it
![foldchange](https://cloud.githubusercontent.com/assets/11674879/11176077/3dbfcedc-8bee-11e5-97cd-8193b4f2af6c.png)

**Comment by rugusf** [comment]
Avg at each position:
![foldchangeavg](https://cloud.githubusercontent.com/assets/11674879/11176208/a746b036-8bef-11e5-954f-6a649b658ee0.png)

**Comment by blueboytrl** [comment]
@rugusf  I don't think  fold change is appropriate.. Because some values are negative some are positive.. say a value in experiment is -0.6, in control is -0.1, you get 6 when you do the ratio,same as 0.6/0,1. You could not tell it is increase or decrease. So I think subtraction may be an alternative way, since we already did the normalizaiton

**Comment by blueboytrl** [comment]
That's why you got a positive 'increased' fitness value at k48 in fold change Mena. vs. Control

**Comment by rugusf** [comment]
I forgot to take the absolute value of the raw fold change before log2, so in this case the fold change will just tell us information on the value not the increase or decrease:

![foldchange](https://cloud.githubusercontent.com/assets/11674879/11176550/fde47114-8bf2-11e5-9ce3-3c4ab7824c1d.png)
![foldchangeavg](https://cloud.githubusercontent.com/assets/11674879/11176551/fdfb6518-8bf2-11e5-9752-7a96390bc178.png)

**Comment by blueboytrl** [comment]
yes, another problem for using the absolute value is that if the value in experiment is negative, say -0.6, but in control is 0.1..You'll get 6 when you do the ratio.. But It is neither 6 times decrease nor 6 times increase.. so i think subtracting control values may be better as I did in the previous heatmaps

**Comment by rugusf** [comment]
but any significant changes at low values will go unnoticed by subtraction

**Comment by blueboytrl** [comment]
What about using subtraction/ abs(control value), in which subtraction shows whether it is increased or decreased, while abs(control) shows the scale?

Sent from my iPhone

On Nov 16, 2015, at 12:03 AM, rugusf <notifications@github.com<mailto:notifications@github.com>> wrote:

but any significant changes at low values will go unnoticed by substraction

**Comment by tlnagy** [comment]
I agree with Ruilin. Abs value for magnitude, but color negative/positive change in two different colors. You can use `np.sign` to get the sign of the difference for example.

**Comment by rugusf** [comment]
This won't be compatible with log...

**Comment by rugusf** [comment]
![signfoldchange](https://cloud.githubusercontent.com/assets/11674879/11191312/818589ca-8c4f-11e5-8ef6-acae81cec73a.png)

**Comment by rugusf** [comment]
@blueboytrl 
my pipeline:

``` python
aa_pos = aa_pos.reset_index()
aa_pos = aa_pos[aa_pos['amino acids'] != '@']
aa_pos = aa_pos[aa_pos['positions'] != 77]
trans_aa_pos = aa_pos.pivot(index = 'amino acids', columns = 'positions', values = 'mean')
trans_aa_pos = trans_aa_pos.reindex(['G', 'A', 'V', 'I', 'L', 'M', 'F', 'Y', 'W', 'C', 'S', 'T', 'P', 'N', 'E', 'D', 
                                     'Q', 'H', 'K', 'R', '*'])
plt.figure(figsize=(20,5))
sns.heatmap(trans_aa_pos[~isnan(trans_aa_pos)], linewidths = 0.001, square = True, vmin = -0.9, vmax = 0.9)
plt.yticks(rotation=0)
plt.title('Menadione Fitness Values')
plt.savefig("mena.png", dpi=300)
```

**Comment by rugusf** [comment]
![foldchange](https://cloud.githubusercontent.com/assets/11674879/11225353/9264659c-8d2e-11e5-95d2-f62df18a6157.png)

**Comment by blueboytrl** [comment]
``` python
wt_ubi = [' ','Q','I','F','V','K','T','L','T','G','K','T','I','T','L','E','V','E','S','S','D','T','I',
                 'D','N','V','K','S','K','I','Q','D','K','E','G','I','P','P','D','Q','Q','R','L','I','F',
                 'A','G','K','Q','L','E','D','G','R','T','L','S','D','Y','N','I','Q','K','E','S','T','L',
                 'H','L','V','L','R','L','R','G','G',' ']
```

**Comment by rugusf** [comment]
updated data:
Day 1 vs. Day 2 fitness values for et0h:
![et0hd1d2](https://cloud.githubusercontent.com/assets/11674879/11321476/ce7b7378-9075-11e5-8526-c6181895a3b6.png)

**Comment by rugusf** [comment]
![controlfitnessheatmap](https://cloud.githubusercontent.com/assets/11674879/11321680/928df7c0-907d-11e5-86d8-44e1efc17dc2.png)
![menafitnessheatmap](https://cloud.githubusercontent.com/assets/11674879/11321679/928ce6aa-907d-11e5-842c-edbae13a2b76.png)

**Comment by tlnagy** [comment]
I would subtract control off like so:

``` python
aa_weighted = pd.read_csv("seq-analysis/data/aa_weighted.csv", index_col=0)
# convert to Multiindex
aa_weighted.set_index(["days", "amino acids", "positions"], append=True, inplace=True)

# subtract control
s1 = aa_weighted.loc[aa_weighted.index.get_level_values("group") != "Control", "weighted mean slope"]
s2 = aa_weighted.loc["Control", "weighted mean slope"]
merged = pd.merge(s1.reset_index(), s2.reset_index(), on=["amino acids", "positions"])
merged["diff"] = merged["weighted mean slope_x"] - merged["weighted mean slope_y"]
merged.drop("days_y", axis=1, inplace=True)
merged.rename(columns={'days_x':'days'}, inplace=True)
merged = merged.set_index(["group", "days", "amino acids", "positions"]).sort_index()
merged.drop("WT", level="amino acids", inplace=True)
merged.drop(["weighted mean slope_x", "weighted mean slope_y"], axis=1, inplace=True)
merged
```

**Comment by tlnagy** [comment]
The bad regression makes sense if you look at the distributions of slopes:

![test15](https://cloud.githubusercontent.com/assets/1661487/11321503/e04690b4-9076-11e5-911d-2d8fc76b9747.png)

**Comment by rugusf** [comment]
not with your code above:
![difffitnessheatmap](https://cloud.githubusercontent.com/assets/11674879/11321678/88b06828-907d-11e5-9442-22d5e2cb6fe5.png)

**Comment by tlnagy** [comment]
If you plot the standard deviations of the fitness slopes across all groups you get the areas of ubiquitin that vary the most between perturbations:
![groups_std](https://cloud.githubusercontent.com/assets/1661487/11321521/be77684a-9077-11e5-9f4f-db36379263d3.png)

**Comment by rugusf** [comment]
^ interesting...
Here's my code for generating all the above heat maps..sorry for the dump:

``` python
aa_weighted = pd.read_csv("data/aa_weighted.csv", index_col=0)
aa_weighted.set_index(["days", "amino acids", "positions"], append=True, inplace=True)
aa_pos_et0h_days = aa_weighted.loc["Et0H", "weighted mean slope"].unstack("days")
aa_pos_ctrl = aa_weighted.loc["Control", "weighted mean slope"].unstack("days")

aa_pos_et0h = pd.DataFrame(aa_pos_et0h_days.mean(1))
aa_pos_et0h.columns = ['mean_fitness']
aa_pos_et0h = aa_pos_et0h.reset_index()

aa_pos_ctrl.columns = ['fitness']
aa_pos_ctrl = aa_pos_ctrl.reset_index()

aa_pos_et0h = aa_pos_et0h[aa_pos_et0h['amino acids'] != 'WT']
aa_pos_ctrl = aa_pos_ctrl[aa_pos_ctrl['amino acids'] != 'WT']
aa_pos_et0h = aa_pos_et0h[aa_pos_et0h['positions'] != 77]
aa_pos_ctrl = aa_pos_ctrl[aa_pos_ctrl['positions'] != 77]

hm_aa_pos_et0h = aa_pos_et0h.pivot(index = 'amino acids', columns = 'positions', values = 'mean_fitness')
hm_aa_pos_ctrl = aa_pos_ctrl.pivot(index = 'amino acids', columns = 'positions', values = 'fitness')
hm_aa_pos_et0h = hm_aa_pos_et0h.reindex(['G', 'A', 'V', 'I', 'L', 'M', 'F', 'Y', 'W', 'C', 'S', 'T', 'P', 'N',
                                         'E', 'D', 'Q', 'H', 'K', 'R', '*'])
hm_aa_pos_ctrl = hm_aa_pos_ctrl.reindex(['G', 'A', 'V', 'I', 'L', 'M', 'F', 'Y', 'W', 'C', 'S', 'T', 'P', 'N',
                                         'E', 'D', 'Q', 'H', 'K', 'R', '*'])
hm_aa_pos_et0h.index.values[-1:] = ['STOP']
hm_aa_pos_ctrl.index.values[-1:] = ['STOP']

hm_aa_pos_et0h_ctrl_diff = np.subtract(hm_aa_pos_et0h, hm_aa_pos_ctrl)

hm_aa_pos_et0h.index.name = 'Amino Acid'
hm_aa_pos_et0h.columns.name = 'Ub Position'
hm_aa_pos_ctrl.index.name = 'Amino Acid'
hm_aa_pos_ctrl.columns.name = 'Ub Position'
hm_aa_pos_et0h_ctrl_diff.index.name = 'Amino Acid'
hm_aa_pos_et0h_ctrl_diff.columns.name = 'Ub Position'

# Control
plt.figure(figsize=(20,5))
sns.heatmap(hm_aa_pos_ctrl[~isnan(hm_aa_pos_ctrl)], linewidths = 0.001, square = True, vmin = -1.5, vmax = 1.5)
plt.yticks(rotation=0)
plt.title('Control Relative Fitness Values')
plt.savefig("controlfitnessheatmap.png", dpi=300)

# Menadione
plt.figure(figsize=(20,5))
sns.heatmap(hm_aa_pos_et0h[~isnan(hm_aa_pos_et0h)], linewidths = 0.001, square = True, vmin = -1.5, vmax = 1.5)
plt.yticks(rotation=0)
plt.title('Menadione Relative Fitness Values')
plt.savefig("menafitnessheatmap.png", dpi=300)

# Difference between Mena and Control
plt.figure(figsize=(20,5))
sns.heatmap(hm_aa_pos_et0h_ctrl_diff[~isnan(hm_aa_pos_et0h_ctrl_diff)], linewidths = 0.001, square = True, 
            vmin = -1.0, vmax = 1.0)
plt.yticks(rotation=0)
plt.title('Difference in Fitness Values between Menadione and Control')
plt.savefig("difffitnessheatmap.png", dpi=300)
```

**Comment by rugusf** [comment]
Although you wouldn't expect much variation in the stop codon

**Comment by tlnagy** [comment]
> Although you wouldn't expect much variation in the stop codon

Why not? The severity of the slope for the stop codon mutant would probably depend on the severity of the perturbation

**Comment by rugusf** [comment]
> Why not? The severity of the slope for the stop codon mutant would probably depend on the severity of >the perturbation

Adding on to this: how can one distinguish between severity of the perturbation itself vs. the nature of the perturbation on its effect of fitness at any codon-pos when comparing across all groups? assuming severity is conc. dependent for a perturbation as well

**Comment by rugusf** [comment]
``` python
# Menadione
#avg at each position
avg_position_et0h = hm_aa_pos_et0h.mean()
sns.set_style("darkgrid")
plt.figure(figsize=(20,5))
plt.title('Menadione: Average Fitness Value at Each Position')
plt.ylabel('Relative Fitness Value')
avg_position_et0h.plot(kind = 'bar')
plt.xticks(rotation=0)
plt.savefig("menaavgpos.png", dpi=300)

#avg at each aa
avg_aa_et0h = hm_aa_pos_et0h.mean(1)
sns.set_style("darkgrid")
plt.figure(figsize=(20,5))
plt.title('Menadione: Average Fitness Value for Each Amino Acid')
plt.ylabel('Relative Fitness Value')
avg_aa_et0h.plot(kind = 'bar')
plt.xticks(rotation=0)
plt.savefig("menaavgaa.png", dpi=300)

# Difference between Mena and Control
#avg at each position
avg_position_et0h_ctrl_diff = hm_aa_pos_et0h_ctrl_diff.mean()
sns.set_style("darkgrid")
plt.figure(figsize=(20,5))
plt.title('Difference between Menadione and Control: Average Difference at Each Position')
plt.ylabel('Difference in Relative Fitness Value')
avg_position_et0h_ctrl_diff.plot(kind = 'bar')
plt.xticks(rotation=0)
plt.savefig("diffavgpos.png", dpi=300)

#avg at each aa
avg_aa_et0h_ctrl_diff = hm_aa_pos_et0h_ctrl_diff.mean(1)
sns.set_style("darkgrid")
plt.figure(figsize=(20,5))
plt.title('Difference between Menadione and Control: Average Difference at Each Amino Acid')
plt.ylabel('Difference in Relative Fitness Value')
avg_aa_et0h_ctrl_diff.plot(kind = 'bar')
plt.xticks(rotation=0)
plt.savefig("diffavgaa.png", dpi=300)
```

![menaavgpos](https://cloud.githubusercontent.com/assets/11674879/11321668/50758470-907d-11e5-9b18-e8ebe6ef21fb.png)
![menaavgaa](https://cloud.githubusercontent.com/assets/11674879/11321669/557dfb6e-907d-11e5-9668-b26d22ca2e58.png)
![diffavgpos](https://cloud.githubusercontent.com/assets/11674879/11321670/5887ab0c-907d-11e5-8b11-03152ff748e1.png)
![diffavgaa](https://cloud.githubusercontent.com/assets/11674879/11321671/5cad1e2e-907d-11e5-9914-3e77693772c1.png)

**Comment by rugusf** [comment]
group of very low fitness values for mena map to a side of Ub:
![pymol2](https://cloud.githubusercontent.com/assets/11674879/11321903/c2bfbfd4-9085-11e5-946b-9b38e24b6596.png)
![menaublowsurface](https://cloud.githubusercontent.com/assets/11674879/11321904/c2db995c-9085-11e5-8443-d70a513d3c84.png)
